### ISSUE TITLE
Sort polluted locations by spotted field when getting them

### ISSUE THREAD

**Issue by BenasB** [vu-vibedosa/apsitvarkom-be#120]
## Description

Sort polluted locations by spotted field when getting them in `GetAll` endpoint. It is up to you to decide if the order should be ascending or descending

## Acceptance criteria

`GetAll` returns sorted polluted locations

**Comment by XxDoMaSxX** [comment]
Currently we have 2 GetAll endpoints in CleaningEventController and  PollutedLocationController. Which one sorting should be done or both of them ?

**Comment by BenasB** [comment]
Ahh yes, you can do them both
