### ISSUE TITLE
Create polluted location reading from a file

### ISSUE THREAD

**Issue by BenasB** [vu-vibedosa/apsitvarkom-be#2]
## Description

Create a class that reads a json file and returns a list of polluted locations.

## Steps to take

1. Create a new class library project `Apsitvarkom.DataAccess` (or similar logical name) where we'll store all data accessing related stuff
2. Create an interface `IPollutedLocationRepository` with one method `GetAllPollutedLocations()`
3. Create an implementation of this interface called `PollutedLocationsFileStore` which implements `GetAllPollutedLocations` by reading a json file. In constructor, take in a file path to a a json file that the class will use as a source. Refer to [MS docs on JSON (de)serialization](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-6-0)
4. Create a test project `Apsitvarkom.UnitTests` (whatever testing framework you prefer).
5. Write a few unit tests for `PollutedLocationsFileStore`

## Acceptance criteria

Implemented `PollutedLocationsFileStore` class with unit testing

**Comment by BenasB** [comment]
Take a look at repository pattern. This is what we're trying to set up in this task.

E. g. https://dotnettutorials.net/lesson/repository-design-pattern-csharp/#:~:text=The%20Repository%20Design%20Pattern%20in%20C%23%20Mediates%20between%20the%20domain,and%20the%20data%20access%20logic.

**Comment by BenasB** [comment]
Having second thoughts about how we want to transfer data. We could use [JsonConstructor](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-immutability?pivots=dotnet-6-0), however we might be better off with another approach:

Have 2 classes representing same domain object in different application layers and map between them, e. g.:
1. `PollutedLocation` class that is used in performing business logic, e. g. calculating distance between locations, etc.
2. `PollutedLocationDTO` a [**D**ata **T**ransfer **O**bject](https://en.wikipedia.org/wiki/Data_transfer_object) representing the data received over REST/HTTP and the data we save into the database.

This way we would have a clear distinction of what's being sent over as responses/taken in as requests, what object is saved to the database AND what object we're performing business logic on.

To map between them, a convenient approach is to use [AutoMapper](https://docs.automapper.org/en/stable/index.html). Please look at it.

So we could achieve this doing something similar:
1. Leave `PollutedLocation` as is
2. Create a `DTO` folder in `Models` project
3. Create DTO classes there (basically what the json brings us):
```csharp
public class PollutedLocationDTO
{
    public string Id { get; init; } = null!;

    public LocationDTO Location { get; set; } = null!;

    public int Radius { get; set; }

    public LocationSeverityLevel Severity { get; set; }

    public DateTime Spotted { get; init; }

    public int Progress { get; set; }

    public string Notes { get; set; } = null!;
}

public class LocationDTO
{
    public double Longitude { get; set; }
    public double Latitude { get; set; }
}
```
4. Create a `Mapping` folder in `Models` project. We'll keep here all of our mapping definitions between those classes.
5. Create a `PollutedLocationProfile` class with the mapping definition. [Profile](https://docs.automapper.org/en/stable/Configuration.html#profile-instances) is a concept of automapper.
```csharp
public class PollutedLocationProfile : Profile
{
    public PollutedLocationProfile()
    {
        CreateMap<PollutedLocationDTO, PollutedLocation>()
            // Everything else that is easily mappable will be done automatically
            // But specify explicitly where we want other mapping logic
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => Guid.Parse(src.Id)));

        CreateMap<LocationDTO, Location>();
    }
}
```
6. Create a configuration and [register it in DI](https://docs.automapper.org/en/stable/Dependency-injection.html#asp-net-core)
7. If a test needs mapping functionality it could look like this (we don't have DI in tests, so we have to create a configration ourselves in the test):
```csharp
[Test]
public void Mapping_HappyPath()
{
    // Should be in test class setup
    var config = new MapperConfiguration(cfg => {
        cfg.AddProfile<PollutedLocationProfile>();
    });

    config.AssertConfigurationIsValid();

    var mapper = config.CreateMapper();

    // Should be in test
    var guidString = "5be2354e-2500-4289-bbe2-66210592e17f";

    // DTO has Id of type string 
    PollutedLocationDTO dto = new()
    {
        Id = guidString,
        Location = new()
        {
            Longitude = -78.948237,
            Latitude = 35.929673
        },
        Radius = 10,
        Severity = Enumerations.LocationSeverityLevel.Moderate,
        Spotted = DateTime.Now,
        Progress = 0,
        Notes = "Hello world"
    };

    // PollutedLocation has Id of type Guid
    var pollutedLocation = mapper.Map<PollutedLocation>(dto);

    Assert.That(pollutedLocation.Id.ToString(), Is.EqualTo(guidString));
}
```

**Comment by 6ar8nas** [comment]
Possible improvements:
Making IPollutedLocationRepository methods async #13 
Validating deserialized DTO objects for mapping #14
