### ISSUE TITLE
Implement Logging

### ISSUE THREAD

**Issue by BaVilius** [vu-vibedosa/apsitvarkom-be#70]
## Description
Log exceptions to a file.
## Steps to take
1. Research logging in .NET.
2. Create a FileLogger that implemnets the methods from ILogger.
3. Create a LoggingProvider that can create an instance of FileLogger.
4. Create an extension method for ILoggingBuilder. This method will be called in `Program.cs` to add logging to file.

## Acceptance criteria

1. All exceptions are logged to a file.

**Comment by BenasB** [comment]
We probably don't want `1. Logger class is created and used via dependency injection.` from Acceptance criteria, since .NET already provides us with `ILogger` to be used for our application by default

**Comment by BaVilius** [comment]
Yep, was just reading about it, will fix description.

**Comment by BenasB** [comment]
@BaVilius could you update the issue description with what we talked about live in person (implementing the 3 things for the logger)?
