### ISSUE TITLE
Research roadmap

### ISSUE THREAD

**Issue by BenasB** [vu-vibedosa/apsitvarkom-be#78]
## Description

As we have discussed sometime earlier, it would be nice to have a timeline/roadmap and plan our remaining time.

## Steps to take

1. Figure out how many development weeks we have left until the final presentation
2. Figure out how many development weeks we have already passed
3. Plan a meeting to discuss the findings and plan what we will do in the upcoming weeks
4. After the meeting, make a short write up on what we're gonna do in the future and post it in "Discussions"

## Acceptance criteria

1. Roadmap plan posted in "Discussions"

**Comment by 6ar8nas** [comment]
#80

**Comment by 6ar8nas** [comment]
Updated #80, moving this issue to done.
