### ISSUE TITLE
Implement PollutedLocationDTODatabaseRepository

### ISSUE THREAD

**Issue by 6ar8nas** [vu-vibedosa/apsitvarkom-be#82]
## Prerequisites

This task requires [infra issue no.13](https://github.com/vu-vibedosa/apsitvarkom-infra/issues/13) and #83 to be completed.

## Description

In [`PollutedLocationDTODatabaseRepository`](https://github.com/vu-vibedosa/apsitvarkom-be/blob/staging/Apsitvarkom.DataAccess/PollutedLocationDTODatabaseRepository.cs#L8) there are some not implemented methods. This task should implement them.

## Steps to take

1. Familiarize yourself with what was done in #83 and how we use EF in our project now (read ["Running locally"](https://github.com/vu-vibedosa/apsitvarkom-be/blob/staging/README.md#running-locally) to learn how to start the project now).
2. Implement 2 not implemented methods in `PollutedLocationDTODatabaseRepository`
3. Look into how EF `DbContext` can be mocked (we're using `Moq` to mock the dependencies, so google something among the lines of "C# moq mock entity framework dbcontext") and try to write some unit tests to cover `PollutedLocationDTODatabaseRepository` behavior.
4. Delete the previously used [JSON file](https://github.com/vu-vibedosa/apsitvarkom-be/blob/staging/Apsitvarkom.Api/PollutedLocationsMock.json) for storing of our PollutedLocationDTO instances. The content from it has been turned into [`DbInitializer`](https://github.com/vu-vibedosa/apsitvarkom-be/blob/staging/Apsitvarkom.DataAccess/DbInitializer.cs#L10)

## Acceptance criteria

1. Fully implemented `PollutedLocationDTODatabaseRepository` with unit testing.

**Comment by BenasB** [comment]
vu-vibedosa/apsitvarkom-infra#13 was implemented, although it does not allow connections from the internet yet. I think we should start with a locally running database (the developer has the DB on their own machine for local development) - from there we can look into hooking up our API to the staging database.

Another point is that 1) we don't have a way to initialize schema/tables in the database (even the staging database is currently empty) and 2) we also don't have a good way of querying the data

Although 1 could be done with [FluentMigrator](https://fluentmigrator.github.io/) and 2 with [Dapper](https://github.com/DapperLib/Dapper), both of these steps should be possible with [Entity Framework](https://learn.microsoft.com/en-us/ef/) (which is a requirement). So my best bet is to start analyzing how entity framework works and trying to use that alongside a locally running database

**Comment by BenasB** [comment]
A good starting point: https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app

**Comment by BenasB** [comment]
Postpone this task until #83 is done, I will update the task description once it's more clear what we should do with this task

**Comment by BenasB** [comment]
Updated this task description, it can be done now
